const en = {
  meta: {
    title: 'Agentic Rioja · AI agents meetups in Logroño, La Rioja',
    description: 'Learn and build AI agents with people in Logroño and La Rioja. In-person meetups with demos and open conversation. Local chapter of the Agentic AI Foundation.',
    imageAlt: 'Agentic Rioja: an illustrated Logroño skyline with a small robot',
  },
  skip: 'Skip to content', home: 'Agentic Rioja: home', menu: 'Menu', mainNav: 'Main', mobileNav: 'Mobile', footerNav: 'Footer',
  nav: [['Topics', '#topics'], ['Meetups', '#events'], ['About', '#about'], ['Organizers', '#organizers'], ['Join', '#join']],
  joinLuma: 'Meetups on Luma',
  hero: { title: 'Learn and build AI agents', accent: 'in La Rioja.', body: 'Meet people in Logroño who share your curiosity about AI agents. Bring your questions or a project to our in-person meetups, and learn from what others are building.', events: 'See upcoming meetups', signoff: '¡Nos vemos en Logroño!', scene: 'Illustration of Logroño: the towers of La Redonda, the Puente de Piedra over the Ebro and Rioja vineyards, with a small robot' },
  affiliation: { region: 'Our foundation', official: 'Official community chapter of', foundation: 'The Agentic AI Foundation is a', project: 'project.' },
  topics: { heading: 'Explore how agents work', intro: 'We share projects and practical lessons about building AI agents. You can join the conversation at any level of experience.', cards: [['AI agents', 'How AI uses tools to carry out tasks, and where it still needs human judgment.'], ['Tools & MCP', 'Connecting agents to files and services with the Model Context Protocol (MCP).'], ['Multi-agent workflows', 'How agents divide tasks and review each other’s work.'], ['Open & vendor-neutral', 'Building with open standards so different tools can work together.']] },
  events: { heading: 'Upcoming meetups', intro: 'We meet in person in Logroño. Find event details and sign up on Luma.', empty: 'We’re planning our first meetup.', follow: 'Follow Agentic Rioja on Luma for the date and venue announcement.', past: 'Past meetups', speakers: 'Speakers:', view: 'View on Luma', notify: 'Get notified on Luma', rsvp: 'RSVP on Luma' },
  meetup: { heading: 'What to expect at a meetup', steps: [['Talks & live demos', 'People walk through their projects and share what worked, what broke, and what they learned.'], ['Open conversation', 'Ask a question, share an idea, or listen in. Beginners are welcome.'], ['Pinchos & conversation', 'We’re in Logroño. There’s room to keep chatting over pinchos afterwards.']] },
  about: { heading: 'Made in La Rioja', p1: 'Learning about AI agents is easier when you have people to share it with. Agentic Rioja gives us a place to meet here in Logroño.', p2: 'We’re a local, vendor-neutral community. Bring the tools you use, the projects you’re trying, and the questions you’re still working through.', sibling: 'Our sibling community.', siblingText: 'For Kubernetes, containers and DevOps, meet Cloud Native Rioja. Our sibling community in La Rioja is part of the', siblingEnd: 'which, like the AAIF, is a Linux Foundation project.', bigger: 'Our wider community', chapter: 'Logroño chapter of the AAIF', chapterText: 'We’re the official Logroño chapter of the Agentic AI Foundation, a Linux Foundation project supporting open agentic AI. Our local meetups are part of that wider community.', aaif: 'About the AAIF', coc: 'Code of Conduct' },
  organizers: { heading: "Who's behind this", intro: 'Meet the organizers bringing Agentic Rioja together. Say hello at a meetup or find us through the links below.', badge: 'organizer badge', website: 'Website' },
  join: { heading: 'Join us in Logroño', intro: 'Start with a meetup. Find the next event or follow us for updates on Luma.', items: [['Come to a meetup', 'Bring your curiosity. You’re welcome even if you haven’t built an agent yet.'], ['Share a project', 'Show us what you’ve tried and what you learned. First-time speakers are welcome.'], ['Offer a venue', 'Have a space in Logroño for a meetup? Get in touch with the organizers.']] },
  footer: { tagline: 'Learning and building AI agents together in Logroño, La Rioja.', official: 'Official chapter of', foundation: 'The Agentic AI Foundation is a', project: 'project.', coc: 'Code of Conduct', privacy: 'Privacy Policy', made: 'Made in Logroño, La Rioja' },
} as const;

const es = {
  meta: { title: 'Agentic Rioja · Encuentros sobre agentes de IA en Logroño, La Rioja', description: 'Aprende y crea agentes de IA con gente de Logroño y La Rioja. Encuentros presenciales con demos y conversación. Capítulo local de la Agentic AI Foundation.', imageAlt: 'Agentic Rioja: una ilustración de Logroño con su perfil urbano y un pequeño robot' },
  skip: 'Saltar al contenido', home: 'Agentic Rioja: inicio', menu: 'Menú', mainNav: 'Principal', mobileNav: 'Móvil', footerNav: 'Pie de página',
  nav: [['Temas', '#topics'], ['Encuentros', '#events'], ['Nosotros', '#about'], ['Organizadores', '#organizers'], ['Participa', '#join']],
  joinLuma: 'Encuentros en Luma',
  hero: { title: 'Aprende y crea agentes de IA', accent: 'en La Rioja.', body: 'Conoce en Logroño a gente que comparte tu curiosidad por los agentes de IA. Trae tus preguntas o un proyecto a nuestros encuentros presenciales y aprende de lo que están creando los demás.', events: 'Ver próximos encuentros', signoff: '¡Nos vemos en Logroño!', scene: 'Ilustración de Logroño: las torres de La Redonda, el Puente de Piedra sobre el Ebro y viñedos riojanos, con un pequeño robot' },
  affiliation: { region: 'Nuestra fundación', official: 'Capítulo oficial de la comunidad', foundation: 'La Agentic AI Foundation es un proyecto de', project: '.' },
  topics: { heading: 'Cómo funcionan los agentes', intro: 'Compartimos proyectos y lo que aprendemos al crear agentes de IA. Puedes participar con cualquier nivel de experiencia.', cards: [['Agentes de IA', 'Cómo usa la IA herramientas para completar tareas y cuándo necesita criterio humano.'], ['Herramientas y MCP', 'Conectar agentes con archivos y servicios mediante el Model Context Protocol (MCP).'], ['Flujos multiagente', 'Cómo se reparten las tareas varios agentes y revisan el trabajo de los demás.'], ['Abierto y neutral', 'Crear con estándares abiertos para que distintas herramientas puedan trabajar juntas.']] },
  events: { heading: 'Próximos encuentros', intro: 'Nos vemos en persona en Logroño. Consulta los detalles de cada encuentro y apúntate en Luma.', empty: 'Estamos preparando el primer encuentro.', follow: 'Sigue a Agentic Rioja en Luma para conocer la fecha y el lugar cuando los anunciemos.', past: 'Encuentros anteriores', speakers: 'Ponentes:', view: 'Ver en Luma', notify: 'Recibir aviso en Luma', rsvp: 'Reservar en Luma' },
  meetup: { heading: 'Qué encontrarás en un encuentro', steps: [['Charlas y demos en directo', 'Compartimos proyectos, lo que salió bien, los fallos y lo que aprendimos por el camino.'], ['Conversación abierta', 'Pregunta, comparte una idea o escucha. También hay sitio para quienes están empezando.'], ['Pinchos y conversación', 'Estamos en Logroño. Podemos seguir charlando después alrededor de unos pinchos.']] },
  about: { heading: 'Hecho en La Rioja', p1: 'Aprender sobre agentes de IA es más fácil cuando tienes con quién compartirlo. Agentic Rioja nos da un lugar para encontrarnos aquí, en Logroño.', p2: 'Somos una comunidad local y neutral respecto a proveedores. Trae las herramientas que usas, los proyectos que estás probando y las dudas que aún tienes.', sibling: 'Nuestra comunidad hermana.', siblingText: 'Si te interesan Kubernetes, los contenedores y DevOps, conoce Cloud Native Rioja. Nuestra comunidad hermana en La Rioja forma parte de la', siblingEnd: 'que, al igual que la AAIF, es un proyecto de la Linux Foundation.', bigger: 'Una comunidad más amplia', chapter: 'Capítulo de la AAIF en Logroño', chapterText: 'Somos el capítulo oficial de Logroño de la Agentic AI Foundation, un proyecto de la Linux Foundation dedicado a la IA agéntica abierta. Nuestros encuentros locales forman parte de esa comunidad.', aaif: 'Sobre la AAIF', coc: 'Código de conducta' },
  organizers: { heading: 'Quién está detrás', intro: 'Conoce a quienes organizamos Agentic Rioja. Salúdanos en un encuentro o contacta con nosotros a través de estos enlaces.', badge: 'distintivo de organizador', website: 'Sitio web' },
  join: { heading: 'Nos vemos en Logroño', intro: 'Empieza por un encuentro. Consulta el próximo evento o síguenos en Luma para recibir las novedades.', items: [['Ven a un encuentro', 'Trae tu curiosidad. Puedes venir aunque todavía no hayas creado un agente.'], ['Comparte un proyecto', 'Enséñanos qué has probado y qué has aprendido. También puedes dar aquí tu primera charla.'], ['Ofrece un espacio', '¿Tienes un espacio en Logroño para un encuentro? Contacta con los organizadores.']] },
  footer: { tagline: 'Aprendemos y creamos agentes de IA juntos en Logroño, La Rioja.', official: 'Capítulo oficial de', foundation: 'La Agentic AI Foundation es un proyecto de', project: '.', coc: 'Código de conducta', privacy: 'Política de privacidad', made: 'Hecho en Logroño, La Rioja' },
};

export const ui = { es, en } as const;
