const en = {
  meta: {
    title: 'Agentic Rioja · The AI agents community in Logroño, La Rioja',
    description: 'Agentic Rioja is the AI agents community in Logroño and La Rioja: meetups with talks, live demos and good conversation. Logroño chapter of the Agentic AI Foundation.',
    imageAlt: 'Agentic Rioja: an illustrated Logroño skyline with a small robot',
  },
  skip: 'Skip to content', home: 'Agentic Rioja: home', menu: 'Menu', mainNav: 'Main', mobileNav: 'Mobile', footerNav: 'Footer',
  nav: [['Topics', '#topics'], ['Meetups', '#events'], ['About', '#about'], ['Organizers', '#organizers'], ['Join', '#join']],
  joinLuma: 'Join us on Luma',
  hero: { title: 'Building AI agents in La Rioja,', accent: 'together.', body: "Agentic Rioja is a community of developers, researchers and curious people from Logroño and the rest of La Rioja. We meet up to show what we're building with AI agents, share what actually works, and keep the conversation going afterwards.", events: 'See upcoming meetups', signoff: '¡Nos vemos en Logroño!', scene: 'Illustration of Logroño: the towers of La Redonda, the Puente de Piedra over the Ebro and Rioja vineyards, with a small robot' },
  affiliation: { region: 'Our foundation', official: 'Official community chapter of', foundation: 'The Agentic AI Foundation is a', project: 'project.' },
  topics: { heading: 'What we talk about', intro: 'New to agents? Perfect. Our meetups mix people who already run agents in production with people who are just getting curious.', cards: [['AI agents', "AI that doesn't just answer questions: it plans, decides and gets things done."], ['Tools & MCP', 'How agents safely connect to your files, APIs and services through open protocols.'], ['Multi-agent workflows', 'Teams of agents that split up the work, hand it over and check each other.'], ['Open & vendor-neutral', 'Open standards so nobody gets locked in, and your agents keep working together.']] },
  events: { heading: 'Upcoming meetups', intro: 'In person, here in Logroño. Grab your spot on Luma.', empty: 'Our first meetup is on its way.', follow: "Follow us on Luma and you'll be the first to know.", past: 'Past meetups', speakers: 'Speakers:', view: 'View on Luma', notify: 'Get notified on Luma', rsvp: 'RSVP on Luma' },
  meetup: { heading: 'What a meetup looks like', steps: [['Talks & live demos', 'Real projects and real code, including what broke along the way. No sales pitches.'], ['Open conversation', 'Questions, ideas and lessons learned. Everyone can join in, beginners included.'], ['Pinchos & networking', 'This is Logroño, after all. The conversation usually carries on over a few pinchos.']] },
  about: { heading: 'Made in La Rioja', p1: "You shouldn't have to travel to Madrid, Barcelona or Bilbao to hear about what's new in AI. There's real talent in La Rioja: developers, researchers, startups and companies already working with AI.", p2: "Agentic Rioja is where we find each other, learn together and build things here. It's a small, friendly and vendor-neutral space where people come to share real work, not slides full of buzzwords.", sibling: 'Our sibling community.', siblingText: 'Into Kubernetes and cloud native? Cloud Native Rioja is the community group for Kubernetes, containers and DevOps in La Rioja, part of the', siblingEnd: 'which, like the AAIF, belongs to the Linux Foundation.', bigger: 'Part of something bigger', chapter: 'Logroño chapter of the AAIF', chapterText: "We're the local chapter of the Agentic AI Foundation, the Linux Foundation's home for open agentic AI. That connects us with builders around the world, including our sister chapter in Silicon Valley.", aaif: 'About the AAIF', coc: 'Code of Conduct' },
  organizers: { heading: "Who's behind this", intro: 'Two locals who love building things and bringing people together. Come and say hi.', badge: 'organizer badge', website: 'Website' },
  join: { heading: 'Come along', intro: "The community is whatever we make it. There's room for everyone.", items: [['Come to a meetup', "You don't need to be an expert. Curiosity is enough."], ['Give a talk', 'Built something with agents, big or small? First-time speakers are very welcome.'], ['Lend us a space', 'Have a venue in Logroño, or want to support the community? Let’s talk.']] },
  footer: { tagline: 'The AI agents community in Logroño, La Rioja.', official: 'Official chapter of', foundation: 'The Agentic AI Foundation is a', project: 'project.', coc: 'Code of Conduct', privacy: 'Privacy Policy', made: 'Made in Logroño, La Rioja' },
} as const;

const es = {
  meta: { title: 'Agentic Rioja · La comunidad de agentes de IA de Logroño, La Rioja', description: 'Agentic Rioja es la comunidad de agentes de IA de Logroño y La Rioja: encuentros con charlas, demostraciones en directo y buena conversación. Capítulo de la Agentic AI Foundation en Logroño.', imageAlt: 'Agentic Rioja: una ilustración de Logroño con su perfil urbano y un pequeño robot' },
  skip: 'Saltar al contenido', home: 'Agentic Rioja: inicio', menu: 'Menú', mainNav: 'Principal', mobileNav: 'Móvil', footerNav: 'Pie de página',
  nav: [['Temas', '#topics'], ['Encuentros', '#events'], ['Nosotros', '#about'], ['Organizadores', '#organizers'], ['Participa', '#join']],
  joinLuma: 'Únete en Luma',
  hero: { title: 'Creando agentes de IA en La Rioja,', accent: 'juntos.', body: 'Agentic Rioja es una comunidad de desarrolladores, investigadores y personas curiosas de Logroño y el resto de La Rioja. Nos reunimos para enseñar lo que estamos creando con agentes de IA, compartir lo que realmente funciona y continuar la conversación después.', events: 'Ver próximos encuentros', signoff: '¡Nos vemos en Logroño!', scene: 'Ilustración de Logroño: las torres de La Redonda, el Puente de Piedra sobre el Ebro y viñedos riojanos, con un pequeño robot' },
  affiliation: { region: 'Nuestra fundación', official: 'Capítulo oficial de la comunidad', foundation: 'La Agentic AI Foundation es un proyecto de', project: '.' },
  topics: { heading: 'De qué hablamos', intro: '¿Es tu primer contacto con los agentes? Perfecto. En nuestros encuentros se mezclan quienes ya usan agentes en producción con quienes empiezan a sentir curiosidad.', cards: [['Agentes de IA', 'Una IA que no solo responde preguntas: planifica, decide y hace el trabajo.'], ['Herramientas y MCP', 'Cómo conectan los agentes de forma segura con tus archivos, API y servicios mediante protocolos abiertos.'], ['Flujos multiagente', 'Equipos de agentes que dividen el trabajo, se lo pasan y se revisan entre ellos.'], ['Abierto y neutral', 'Estándares abiertos para evitar dependencias y mantener tus agentes trabajando juntos.']] },
  events: { heading: 'Próximos encuentros', intro: 'En persona, aquí en Logroño. Reserva tu plaza en Luma.', empty: 'Nuestro primer encuentro está en camino.', follow: 'Síguenos en Luma y serás la primera persona en enterarte.', past: 'Encuentros anteriores', speakers: 'Ponentes:', view: 'Ver en Luma', notify: 'Recibir aviso en Luma', rsvp: 'Reservar en Luma' },
  meetup: { heading: 'Cómo es un encuentro', steps: [['Charlas y demostraciones', 'Proyectos y código reales, incluyendo lo que falló por el camino. Sin discursos de venta.'], ['Conversación abierta', 'Preguntas, ideas y lecciones aprendidas. Todo el mundo puede participar, también principiantes.'], ['Pinchos y networking', 'Estamos en Logroño. La conversación suele continuar alrededor de unos pinchos.']] },
  about: { heading: 'Hecho en La Rioja', p1: 'No debería hacer falta viajar a Madrid, Barcelona o Bilbao para conocer las novedades en IA. En La Rioja hay talento real: desarrolladores, investigadores, startups y empresas que ya trabajan con IA.', p2: 'Agentic Rioja es el lugar donde encontrarnos, aprender juntos y construir cosas aquí. Un espacio pequeño, cercano y neutral donde compartir trabajo real, no diapositivas llenas de palabras de moda.', sibling: 'Nuestra comunidad hermana.', siblingText: '¿Te interesan Kubernetes y el cloud native? Cloud Native Rioja es la comunidad de Kubernetes, contenedores y DevOps en La Rioja, parte de la', siblingEnd: 'que, como la AAIF, pertenece a la Linux Foundation.', bigger: 'Parte de algo más grande', chapter: 'Capítulo de la AAIF en Logroño', chapterText: 'Somos el capítulo local de la Agentic AI Foundation, el hogar de la Linux Foundation para la IA agéntica abierta. Esto nos conecta con personas que crean tecnología en todo el mundo, incluido nuestro capítulo hermano de Silicon Valley.', aaif: 'Sobre la AAIF', coc: 'Código de conducta' },
  organizers: { heading: 'Quién está detrás', intro: 'Dos personas de aquí a las que les encanta crear cosas y reunir a la gente. Ven a saludarnos.', badge: 'distintivo de organizador', website: 'Sitio web' },
  join: { heading: 'Participa', intro: 'La comunidad será lo que hagamos entre todos. Hay sitio para todo el mundo.', items: [['Ven a un encuentro', 'No necesitas ser experto. Con tener curiosidad es suficiente.'], ['Da una charla', '¿Has creado algo con agentes, grande o pequeño? Las primeras charlas son muy bienvenidas.'], ['Préstanos un espacio', '¿Tienes un espacio en Logroño o quieres apoyar a la comunidad? Hablemos.']] },
  footer: { tagline: 'La comunidad de agentes de IA de Logroño, La Rioja.', official: 'Capítulo oficial de', foundation: 'La Agentic AI Foundation es un proyecto de', project: '.', coc: 'Código de conducta', privacy: 'Política de privacidad', made: 'Hecho en Logroño, La Rioja' },
};

export const ui = { es, en } as const;
